name: fake_process_manager
description: Process Manager for faking processes in tests. Taken from Flutter Tools.
version: 0.2.0
homepage: https://github.com/mmcc007/fake_process_manager
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  process: ^4.0.0-nullsafety.2
  tool_base: ^2.0.0
  mockito: ^4.1.0
  test: ^1.6.0
dev_dependencies:
  pedantic: ^1.7.0
  tool_base_test:
    git: https://github.com/mmcc007/tool_base_test.git
#    path: ../tool_base_test
